### PR TITLE
POST parameters were not passed when uploading files

### PR DESCRIPTION
**Pull request by Saso222**
I've added a couple lines of code to pass the parameters that were configured in the config.api section to the formData extra params that will be passed to the jQuery.fileupload plugin. Thus, those extra params will be received in the connector.

This was totally necessary when having a separated server for the files, due to the insexistent session held between both HTML and files server. So, the params that you want to have in the connector are necessarily passed in every request made.

### CODE REVIEW

**Comment by servocoder** [comment]
Good catch, thanks!

One note: Object.assign isn't supported by IE so I will replace this method preserving the functionality of your PR

**Comment by servocoder** [comment]
Ok, I have reworked your code and it should work as expected for all requests including jQuery.fileupload respecting IE browser. Also note that config.api MIXED params are passed to jQuery.fileupload as well. Check all methods again please and let me know whether all the things work as designed. Once you back with positive result I will merge the updates to the master branch.

**Comment by Saso222** [comment]
It is working as intended, yep.

Thank you very much!

**Comment by servocoder** [comment]
Awesome! I'm going to merge it with master the coming days.

**Comment by Saso222** [comment]
Hey,

I just realised something: When creating the images urls, more concretely those for the thumbnails, it was not sending the parameters. I wasn't being able to see the thumbnails because of this.

I added the following line to the 'createImageUrl' function to add them:

`queryParams = extendRequestParams("GET", queryParams);`

Do you want me to make the PR? Is this intended?

Best regards.

**Comment by servocoder** [comment]
Indeed. This is a curious observation.

If we declare that `config.api` is passed with every connector request, then we have to be make sure that we cover all `buildConnectorUrl()` methods calls by extending params which it accepts. I can see few not covered `buildConnectorUrl()` method params in the following locations:

- `createImageUrl()` function
- `createPreviewUrl()` function
- `MarkdownRenderer()` function

Go ahead and create new PR, perhaps you will be able to find some other issues during the process.

**Pull request merged**
