### PR TITLE
Updated ashx connector and some bug fixes

### PR DESCRIPTION
**Pull request by richeflits**
Made an basic ashx connector using a StringWriter to generate json responses. I think it's a good idea to extend the handler in the futher with Newtonsoft Json for a more reliable json generation. But for now this solution works (tested in .Net 4)

I also fixed the extension display in list view and a broken img displayed on the back to parent icon.

This is my first commit to a GitHub repository, so i hope i did it the right way :)

### CODE REVIEW

**Comment by servocoder** [comment]
Wow, that's great!
I'm going to review and merge your PR in the coming days.
Hope you will continue to maintain ashx connector.
Thanks for your contribution.

**Comment by servocoder** [comment]
Could I expect that you will continue to improve and maintain ashx connector? If so I would ask you to provide some configuration file for ashx connector as it's done [for php connector](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/config.php). I don't expect that it will be the same extensive, but it's a good practice to move some configurable options to a separate file. Thanks in advance.

**Comment by richeflits** [comment]
Yes, i will move some settings to a configuration file.
Currently I am very busy, so first i need to find some time.
We’ll keep in touch.

**Comment by servocoder** [comment]
Great, thanks!

**Pull request merged**
