### PR TITLE
Added redirect functionality for non authorized users

### PR DESCRIPTION
**Pull request by SalimSalici**
I've added the possibility to redirect a user to another page if the initial authorization fails (so it won't show the loader indefinitely).

I've also made some updates to the Italian translations.

Lastly, if a user was not authorized, the error message showed the text "AUTHORIZATION REQUIRED" instead of "You are not authorized to use filemanager.". To solve this I moved the language file request before the initial request.

This is my first contribution to an open source project ever, so I hope I didn't mess up something :)

### CODE REVIEW

**Comment by servocoder** [comment]
Thanks for the contribution. At the moment I perform a major update for PHP connector. You can follow it at the "refactored" branch. Once it complete it I will condider your PR.

**Comment by SalimSalici** [comment]
Ok, should I close this pull request and make the same thing for the refactored code?

**Comment by servocoder** [comment]
Oh, I was very busy recently and I totally forgot of your PR.
Sure, please make it compatible with the latest version and I will merge it.

**Comment by SalimSalici** [comment]
Alright.

**Pull request closed without merging**
