### PR TITLE
fix: Added timezone setting to fix fatal error

### PR DESCRIPTION
**Pull request by djb15**
After posting my issue earlier I managed to find a fix.  Initially the master branch fails completely as explained before.  With the "filemanager.min.js" file the browser console does not throw any useful errors. After changing to the non minified version I also edited the ajax error function in the "getFolderData" function in "filemanager.js" as shown below to give me a useful error in the console: 
screen shot 2016-09-08 at 13 49 08
The error I received is shown here:
screen shot 2016-09-08 at 13 50 32
Since the modified ajax error function didn't help solve the error I returned it to its previous state.  

So the fix I implemented was adding the one line to "filemanager.php" specifying a timezone.  My knowledge of PHP isn't very good so there is probably a way to implement this through the "filemanager.config.json" file so the user can specify their own timezone, but for now this proved a good fix for me and solved all my issues. 

I hope this all makes sense. Thanks!

### CODE REVIEW

**Comment by servocoder** [comment]
Interesting. I will check it later. Thank you for posting the solution for #43

**Comment by servocoder** [comment]
Fixed with the latest commit.

**Comment by djb15** [comment]
Thanks for all the help with the PHP stuff! Just to let you know I have started development of the python connector.

**Comment by servocoder** [comment]
Great!
And it would be better if you use "dev" branch.
It is contain structural changes (and some in progress) which will be merged with master when are finished, so you will have to rewrite your connector if you do it based on the "master" branch. I am going to describe all of them today/tomorrow and will let you know.

For the further discussion on Python connector I suggest you to create new "Python connector" issue.

**Pull request closed without merging**
