### PR TITLE
JSP Connector Update

### PR DESCRIPTION
**Pull request by gmkll**
Fixing to API changes (current RFM version 2.5.x),  bugfixing, updating, i.e. making more coherent to and partially following java connector using helper functions error/util. Main difference may be context and upload handling, file cleanup function, Java 7 and lower servlet API 2.5 requirements, consolidating process may start in a later step. Cleanup resources, changed package using gradle. TODOS cft. readme.

### CODE REVIEW

**Comment by servocoder** [comment]
Thanks a lot!
I can see you made updates for both /jsp and /java connectors. Awesome!
I talked to @fabriceci and he wish to discuss some points with you, since he is developer of /java connector.
Could you print your Skype id to speed up the communication?

**Comment by gmkll** [comment]
Hi Pavel,

my id is tancredini, but I am not online with Skype in the moment. 

We could discuss via e-mail as well? Or just open an issue, if he likes 
also here https://github.com/gmkll/RichFilemanager

Let me know about, what you discussed! It´s a work in progress of course 
;-)

Best regards, Georg

**Comment by servocoder** [comment]
I would prefer Skype. What time you are online in Skype generally?
Hope you will find a convenient way to chat

**Comment by gmkll** [comment]
ok, I ´ll update my skype settings. Next week I am not online before Tuesday, otherwise afternoons are best, except may be Friday. CU

**Comment by servocoder** [comment]
Ok, me and @fabriceci have already sent request to you in Skype. Ping us once you are online, please.

**Pull request merged**
